import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { RoomClient } from "@/components/RoomClient";
import { normalizeRoomCode, isValidRoomCode } from "@/lib/roomCode";

// Rich link preview for shared room links (the OG image is generated by the
// sibling opengraph-image.tsx).
export async function generateMetadata({
  params,
}: {
  params: Promise<{ code: string }>;
}): Promise<Metadata> {
  const { code } = await params;
  const room = normalizeRoomCode(code);
  const title = `Join room ${room} on Voiceapp`;
  const description =
    "Talk together, instantly — no install, no account needed.";
  return {
    title,
    description,
    openGraph: { title, description, type: "website" },
    twitter: { card: "summary_large_image", title, description },
  };
}

export default async function RoomPage({
  params,
}: {
  params: Promise<{ code: string }>;
}) {
  const { code } = await params;
  const normalized = normalizeRoomCode(code);

  if (!isValidRoomCode(normalized)) {
    notFound();
  }

  return <RoomClient code={normalized} />;
}
